sfGuardUserProfileStuff:
  actAs:
    Timestampable: ~
  tableName: sf_guard_user_profile
  columns:
    user_id:
      type: integer(4)
      notnull: true
    email:
      type: string(80)
      notnull: true
      unique: true
    new_password: 
      type: string(128)
    new_password_created_at:
      type: timestamp
    activation_key:
      type: string(32)
    validate_at:
      type: timestamp
    validate:
      type: string(33)
